[project]
name = "test1"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]

[build]
syntax_style = "Rust"
optimization_level = 2
debug_info = true
source_maps = true

[targets.typescript]
enabled = true
module_system = "es2020"
emit_types = true
strict = true

[targets.wasm-component]
enabled = false
with_wit = true
generate_bindings = true
wit_package = "test1"

[lsp]
enabled = true
port = 9257
features = ["completions", "hover", "goto-definition", "find-references"]
